// <auto-generated />
namespace Electrodevices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPath_Picture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPath_Picture));
        
        string IMigrationMetadata.Id
        {
            get { return "202302151842009_Add Path_Picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
